# Generated by Django 2.1.3 on 2018-11-27 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '讨论帖', 'verbose_name_plural': '讨论帖'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': '项目', 'verbose_name_plural': '项目'},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name': '讨论回复', 'verbose_name_plural': '讨论回复'},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'verbose_name': '资源', 'verbose_name_plural': '资源'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': '任务', 'verbose_name_plural': '任务'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AlterModelOptions(
            name='userinproject',
            options={'verbose_name': '用户 - 项目关系', 'verbose_name_plural': '用户 - 项目关系'},
        ),
        migrations.AlterModelOptions(
            name='userintask',
            options={'verbose_name': '用户 - 任务关系', 'verbose_name_plural': '用户 - 任务关系'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='userinproject',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='userinproject',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userintask',
            old_name='task_id',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='userintask',
            old_name='user_id',
            new_name='user',
        ),
    ]
